[ADD] osi_analytic_segments_defaults
ursais/osi-addons pull request #122
Opened 2019-06-27 14:53 UTC by max3903

2019-07-09 12:38 UTC, murtuzasaleh commented
Depends on #117

2019-07-10 14:16 UTC, mgosai commented on osi_analytic_segments_defaults/README.rst
> +* Open Source Integrators <http://www.opensourceintegrators.com>
Swap the names between contributors and credits

2019-07-10 14:17 UTC, mgosai requested changes
Swap the names between contributors and credits.

2019-07-10 14:27 UTC, murtuzasaleh commented
> Swap the names between contributors and credits.

Done

2019-07-10 14:39 UTC, mgosai approved these changes

2019-07-10 15:10 UTC, merged