[ADD] osi_analytic_segments_expenses
ursais/osi-addons pull request #125
Opened 2019-06-27 14:53 UTC by max3903

2019-07-09 11:36 UTC, murtuzasaleh commented
Depends on #117

2019-07-10 14:19 UTC, mgosai requested changes
Again, Swap the names between contributors and credits.

2019-07-10 14:32 UTC, murtuzasaleh commented
> Again, Swap the names between contributors and credits.

Done

2019-07-10 14:39 UTC, mgosai approved these changes

2019-07-10 15:09 UTC, merged