[WIP][ADD][12.0] fieldservice_account_asset
ursais/osi-addons pull request #170
Opened 2019-07-31 10:09 UTC by murtuzasaleh

#93

2019-08-02 13:01 UTC, murtuzasaleh commented on fieldservice_account_asset/models/fsm_equipment.py
> +        self.change_equipment_stage()
@max3903 Can we need to call our functionality in this method?
If yes, It will create move and asset multiple time based on condition.

2019-08-02 13:01 UTC, murtuzasaleh commented
@max3903 Can you please review this PR.

2019-09-04 14:37 UTC, bodedra requested changes
Minor comments

2019-09-04 14:37 UTC, bodedra commented on fieldservice_account_asset/models/fsm_equipment.py
> +                ('account_id', '=', self.asset_id.category_id.account_depreciation_expense_id.id)])
```suggestion
                ('account_id', '=', equipment.asset_id.category_id.account_depreciation_expense_id.id)])
```

2019-09-04 14:37 UTC, bodedra commented on fieldservice_account_asset/models/fsm_equipment.py
> +            self.asset_id = False
```suggestion
            equipment.asset_id = False
```

2019-09-04 14:37 UTC, bodedra commented on fieldservice_account_asset/models/fsm_equipment.py
> +            self.asset_location_id = False
```suggestion
            equipment.asset_location_id = False
```

2019-09-04 14:37 UTC, bodedra commented on fieldservice_account_asset/models/fsm_equipment.py
> +            self.asset_location_id = equipment.current_stock_location_id.id
```suggestion
            equipment.asset_location_id = equipment.current_stock_location_id.id
```

2019-09-04 14:37 UTC, bodedra commented on fieldservice_account_asset/models/fsm_equipment.py
> +                    self.asset_recover()
```suggestion
                    equipment.asset_recover()
```

2019-09-04 14:37 UTC, bodedra commented on fieldservice_account_asset/models/fsm_equipment.py
> +                equipment.asset_id = self.asset_create()
```suggestion
                equipment.asset_id = equipment.asset_create()
```

2019-09-04 15:56 UTC, max3903 commented
Thanks @bodedra! Good catch.

2019-09-04 16:43 UTC, bodedra commented
@murtuzasaleh Thanks for your work. Would you please fix following test_flake8 .

![Firefox_Screenshot_2019-09-04T16-41-40 137Z](https://user-images.githubusercontent.com/14229503/64274472-13a70100-cf61-11e9-8841-ca92bd385a95.png)

2019-09-04 17:25 UTC, merged