[IMP] Add FSM Location to SRO's + SR's
ursais/osi-addons pull request #207
Opened 2019-10-23 22:13 UTC by osi-scampbell

Ticket #1122

This PR adds FSM Locations to SR's and SRO's. Instead of going through the context I elected to handle the login in the create() and the onchange().

2019-10-23 22:18 UTC, max3903 approved these changes

2019-10-23 22:18 UTC, max3903 commented
@osi-scampbell Can you add a test to cover that scenario?

2019-10-24 05:09 UTC, bodedra approved these changes
LGTM :+1: 

@osi-scampbell It would be good if we make travis-ci green.

![Firefox_Screenshot_2019-10-24T05-07-35 062Z](https://user-images.githubusercontent.com/14229503/67455183-8754b880-f64a-11e9-8c68-6d3278f4e375.png)

2019-10-24 15:40 UTC, osi-scampbell commented
> LGTM 👍
> 
> @osi-scampbell It would be good if we make travis-ci green.
> 
> ![Firefox_Screenshot_2019-10-24T05-07-35 062Z](https://user-images.githubusercontent.com/14229503/67455183-8754b880-f64a-11e9-8c68-6d3278f4e375.png)

I totally forgot about the lint errors...thanks for pointing that out @bodedra, I'll take care of that now

2019-10-24 16:47 UTC, max3903 commented on fieldservice_helpdesk_stock/tests/__init__.py
> +# Copyright (C) 2019 - TODAY, Open Source Integrators
```suggestion
# Copyright (C) 2019 Open Source Integrators
```

2019-10-24 16:47 UTC, max3903 commented on fieldservice_helpdesk_stock/tests/test_stock_request.py
> +# Copyright 2017 Eficent Business and IT Consulting Services S.L.
```suggestion
# Copyright (C) 2019 Open Source Integrators
```

2019-10-24 16:47 UTC, max3903 commented on fieldservice_helpdesk_stock/views/stock_request.xml
> +<?xml version="1.0" encoding="utf-8"?>
```suggestion
```

2019-10-24 16:47 UTC, max3903 commented on fieldservice_helpdesk_stock/views/stock_request_order.xml
> +<?xml version="1.0" encoding="utf-8"?>
```suggestion
```

2019-10-24 16:48 UTC, max3903 requested changes
Few cosmetic changes.

2019-10-24 20:42 UTC, max3903 commented
@osi-scampbell Can you rebase this branch to get it green?

2019-10-24 21:18 UTC, osi-scampbell commented
@max3903 Branch rebased, commits squashed

2019-10-25 06:00 UTC, bodedra commented
Yay. It's :green_apple: now.

2019-10-25 12:02 UTC, max3903 approved these changes

2019-10-25 12:02 UTC, merged