[ADD]New module to add address auto-completition for FSM location
ursais/osi-addons pull request #21
Opened 2018-12-13 17:15 UTC by osimallen

Created a new module to add address auto-completion and geometry sync between orders and associated locations.

2018-12-13 20:26 UTC, max3903 requested changes
Can you rename the module to fieldservice_googlemaps with underscore?

2018-12-13 20:26 UTC, max3903 commented on fieldservice-googlemaps/__init__.py
> +from . import models
Missing newline

2018-12-13 20:26 UTC, max3903 commented on fieldservice-googlemaps/models/__init__.py
> +from . import fsm_location, fsm_order
Missing newline

2018-12-13 20:26 UTC, max3903 commented on fieldservice-googlemaps/models/fsm_location.py
> +                                                longitude=lng)
Wrong indentation

2018-12-13 20:26 UTC, max3903 commented on fieldservice-googlemaps/models/fsm_order.py
> +
Empty lines to remove

2018-12-13 20:26 UTC, max3903 commented on fieldservice-googlemaps/views/fsm_location.xml
> +
Empty lines to remove

2018-12-13 20:29 UTC, max3903 commented on fieldservice-googlemaps/__manifest__.py
> +        'web_google_maps',
`'fieldservice',`?

2018-12-13 20:48 UTC, osimallen commented on fieldservice-googlemaps/__init__.py
> +from . import models
Resolved in latest commit

2018-12-13 20:48 UTC, osimallen commented on fieldservice-googlemaps/models/__init__.py
> +from . import fsm_location, fsm_order
Resolved in latest commit

2018-12-13 20:48 UTC, osimallen commented on fieldservice-googlemaps/models/fsm_location.py
> +                                                longitude=lng)
Resolved in latest commit

2018-12-13 20:48 UTC, osimallen commented on fieldservice-googlemaps/models/fsm_order.py
> +
Resolved in latest commit

2018-12-13 20:48 UTC, osimallen commented on fieldservice-googlemaps/views/fsm_location.xml
> +
Resolved in latest commit

2018-12-13 20:48 UTC, osimallen commented on fieldservice-googlemaps/__manifest__.py
> +        'web_google_maps',
Resolved in latest commit

2018-12-14 03:01 UTC, max3903 approved these changes

2018-12-14 03:02 UTC, merged