[12.0][ADD] fieldservice_sign
ursais/osi-addons pull request #221
Opened 2019-12-02 07:54 UTC by murtuzasaleh

For Mobile Application Sign URL Functionality.

2019-12-02 07:54 UTC, murtuzasaleh commented
@dreispt @max3903

2019-12-02 14:54 UTC, max3903 commented on fieldservice_sign/__manifest__.py
> +# Copyright (C) 2019 Open Source Integrators
```suggestion
# Copyright (C) 2019 Open Source Integrators
# Copyright (C) 2019 Serpent Consulting Services Pvt. Ltd.
```

2019-12-02 14:54 UTC, max3903 commented on fieldservice_sign/models/fsm_order.py
> +# Copyright (C) 2019 Open Source Integrators
```suggestion
# Copyright (C) 2019 Open Source Integrators
# Copyright (C) 2019 Serpent Consulting Services Pvt. Ltd.
--



```

2019-12-02 14:55 UTC, max3903 commented on fieldservice_sign/models/sign_request.py
> +# Copyright (C) 2019 Open Source Integrators
```suggestion
# Copyright (C) 2019 Open Source Integrators
# Copyright (C) 2019 Serpent Consulting Services Pvt. Ltd.
```

2019-12-02 14:55 UTC, max3903 commented on fieldservice_sign/wizard/sign_send_request.py
> +# Copyright (C) 2019 Open Source Integrators
```suggestion
# Copyright (C) 2019 Open Source Integrators
# Copyright (C) 2019 Serpent Consulting Services Pvt. Ltd.
```

2019-12-02 14:57 UTC, max3903 requested changes
Minor changes.

2019-12-12 08:06 UTC, murtuzasaleh commented
@dreispt Can you please review this PR.

2019-12-12 08:49 UTC, dreispt approved these changes
LGTM
A made a couple of improvement suggestions.

2019-12-12 08:49 UTC, dreispt commented on fieldservice_sign/views/fsm_order.xml
> +                <page name="signature" string="Signature">
```suggestion
                <page name="signature" string="Signed Documents">
```

2019-12-12 08:49 UTC, dreispt commented on fieldservice_sign/wizard/sign_send_request.py
> +        return {
I'm guessuig that `res` is a Client Action dict.
If so, we can simplify this and just `return res`, instead of redefining the Client Action.

2019-12-13 15:16 UTC, dreispt commented on fieldservice_sign/wizard/sign_send_request.py
> +        return {
Sorry, my bad - this is not an inherited method, should be OK as is.

2019-12-13 15:36 UTC, dreispt commented on fieldservice_sign/wizard/sign_send_request.py
> +        return res
It's calling super() now!
👍

2019-12-13 15:36 UTC, dreispt approved these changes

2019-12-16 11:09 UTC, merged