[IMP] Set Carrier on Pickings
ursais/osi-addons pull request #266
Opened 2020-05-15 18:21 UTC by osi-scampbell

This PR resolves ticket #1853 Medium: Stock Requests - Multiple issues with missing analytic accounts context. All items related to carrier_id I kept here in helpdesk_delivery. One concern I have is helpdesk_stock and fieldservice_stock are very different and keeping functionality the same from both sides appears to be tricky. I addec these classes on stock_request.py because they are all small and are all working together. I can split them up if we think that is best or change the .py file to stock.py. Please let me know and I will make sure it is done before the QA release

2020-05-16 14:49 UTC, max3903 requested changes
@osi-scampbell Can you split this file by model?

2020-05-18 13:33 UTC, mgosai requested changes
As @max3903 mentioned split file

2020-06-18 17:30 UTC, osi-scampbell commented
@max3903 @mgosai @bodedra Files split

2020-06-18 17:44 UTC, max3903 approved these changes

2020-06-23 19:57 UTC, patrickrwilson approved these changes
LGTM

2020-06-23 20:06 UTC, merged