[13.0][MIG] sale_subscription_suspend
ursais/osi-addons pull request #283
Opened 2020-08-13 17:43 UTC by murtuzasaleh

Subscription Suspensions
====================
Suspend and Re-Activate your sales subscriptions

2020-08-13 18:18 UTC, max3903 commented on .travis.yml
> +
```suggestion
```

2020-08-14 13:11 UTC, max3903 approved these changes

2020-08-14 15:23 UTC, bodedra requested changes

2020-08-14 15:23 UTC, bodedra commented on sale_subscription_suspend/models/sale_subscription.py
> +        subscription_stage_obj = self.env["sale.subscription.stage"]
```suggestion
        subscription_stage_obj = self.env["sale.subscription.stage"]
        stage = subscription_stage_obj.search([("in_progress", "=", True)], limit=1)
        if stage:
            self.write({"stage_id": stage.id, "to_renew": False, "date": False})
```

2020-08-14 15:23 UTC, bodedra commented on sale_subscription_suspend/models/sale_subscription.py
> +        for sub in self:
```suggestion

```

2020-08-14 15:23 UTC, bodedra commented on sale_subscription_suspend/models/sale_subscription.py
> +            stage = subscription_stage_obj.search([("in_progress", "=", True)], limit=1)
```suggestion
```

2020-08-14 15:23 UTC, bodedra commented on sale_subscription_suspend/models/sale_subscription.py
> +            sub.write({"stage_id": stage.id, "to_renew": False, "date": False})
```suggestion
```

2020-10-01 12:01 UTC, merged