[FIX] missing dependency
ursais/osi-addons pull request #308
Opened 2021-01-20 16:21 UTC by bodedra

'resolution' field introduced in helpdesk_resolution module. Ref: https://github.com/ursais/osi-addons/blob/12.0/helpdesk_resolution/models/helpdesk_ticket.py

We have used that field in close ticket event. Ref: https://github.com/ursais/osi-addons/blob/12.0/helpdesk_fieldservice/wizard/fsm_order_close_wizard.py#L20

2021-01-20 16:33 UTC, max3903 approved these changes

2021-01-20 16:34 UTC, max3903 requested changes
I would remove the line in the wizard instead of adding the dependency.

2021-01-20 16:38 UTC, bodedra commented
@Chanakya-SerpentCS Would you please take care of this? Remove line from helpdesk_fieldservice module and improve logic on helpdesk_resolution module.

2021-01-22 15:52 UTC, bodedra commented
@Chanakya-SerpentCS will improve following points:

1. In helpdesk_resolution, set dependency of helpdesk_fieldservice
2. Override wizard close method ------ We are set resolution value from ticket_id and it declared in helpdesk_fieldservice 
3. Remove line from helpdesk_fieldservice

@max3903 Will it work for you?

JFI, we have to set hard dependency either way.

2021-01-22 16:09 UTC, max3903 commented
@bodedra @Chanakya-SerpentCS 

Those 2 modules should not depend on each other.

Option 1 (recommended): Use `helpdesk_stage_server_action` to configure an action on the close stage to check that the resolution field is set.
Option 2: Extend the wizard method in a private module to check the resolution field.

2022-02-06 12:08 UTC, closed without merging