14 mig osi account bank statement dr
ursais/osi-addons pull request #310
Opened 2021-01-26 10:25 UTC by dreispt

- [IMP] Version 14.0
- [ADD] osi_account_bank_statement (#168)
- [FIX] osi_account_bank_statement: AttributeError: 'account.journal' object has no attribute 'liability_account_id'
- [IMP] osi_account_bank_statement: black, isort, prettier
- [MIG] osi_account_bank_statement: port to 14.0

2021-01-27 22:16 UTC, mgosai requested changes
Some files are having copyright from 2019 while other from 2020
can we have all in sync ? bdw it's already 2021 ;)  
Also, as stated for v13 module. We will be having separate module for all bank rec related patches and will not manipulate this module. 
@bodedra will be handling it

2021-01-27 22:16 UTC, mgosai commented on osi_account_bank_statement/__manifest__.py
> +    "version": "13.0.1.0.1",
should be v14

2021-02-05 10:37 UTC, dreispt commented
@mgosai The copyright year is good as it is: is should match the work's creation date.
Later work can have later dates.
Older dates should stay like that, to properly claim authorship and protect copyright.

2022-01-27 19:01 UTC, smangukiya commented
closing this out because this is not properly migrated to v14 with current PR.
new PR https://github.com/ursais/osi-addons/pull/423

2022-01-27 19:01 UTC, closed without merging