[ADD] osi_fifo_serialized_fix
ursais/osi-addons pull request #311
Opened 2021-01-28 23:45 UTC by max3903

2021-02-16 20:44 UTC, b-kannan commented
@osi-scampbell @agyamuta The stock_quant.py change (last commit) only considers lot and not lot. What about serial number quants?

2021-02-16 21:20 UTC, osi-scampbell commented
> @osi-scampbell @agyamuta The stock_quant.py change (last commit) only considers lot and not lot. What about serial number quants?

@b-kannan I think I got tunnel vision and only wrote a cases for Lot and SN. The 'else' in this case is supposed to be for SN tracked objects, however I believe this would affect products with no tracking which is not intended. The commit I just pushed alters the method to only check for Lot and SN, if it is not tracked, then we will use core odoo workflow.

2021-02-17 18:25 UTC, b-kannan commented
> > @osi-scampbell @agyamuta The stock_quant.py change (last commit) only considers lot and not lot. What about serial number quants?
> 
> @b-kannan I think I got tunnel vision and only wrote a cases for Lot and SN. The 'else' in this case is supposed to be for SN tracked objects, however I believe this would affect products with no tracking which is not intended. The commit I just pushed alters the method to only check for Lot and SN, if it is not tracked, then we will use core odoo workflow.

Thank you.

2021-02-19 03:21 UTC, max3903 commented on osi_fifo_serialized_fix/models/stock_quant.py
> +                        else if quant.product_id.tracking == 'serial':
```suggestion
                        elif quant.product_id.tracking == 'serial':
```

2021-02-19 03:23 UTC, max3903 commented on osi_fifo_serialized_fix/views/stock_valuation_layer.xml
> +<odoo>
```suggestion
<odoo>
```

2021-07-16 19:03 UTC, sorrytosay commented on osi_fifo_serialized_fix/models/stock_move.py
> +                                val['quantity'] = line_id.qty_done * -1
For outgoing

2021-07-16 19:13 UTC, sorrytosay requested changes
For an outgoing transfer, the 'value' in SVL layer should be negative. It becomes positive. val['value'] = val_obj.unit_cost * val['quantity'] *  -1

2021-07-16 19:13 UTC, sorrytosay commented on osi_fifo_serialized_fix/models/stock_move.py
> +                            val['value'] = val_obj.unit_cost * val['quantity'] * -1
For outgoing transfesr, the 'value' in SVL layer should be negative. It becomes positive. value['value'] = val_obj.unit_cost * val['quantity'] *  -1

2022-02-22 13:12 UTC, patrickrwilson approved these changes
This is an old PR but used in some projects for a while now. This looks good to me so we should move it forward.

2022-02-22 20:05 UTC, merged