[12.0][IMP] Exposed fsm_quantity field and added conditional coloring
ursais/osi-addons pull request #314
Opened 2021-02-11 19:38 UTC by ReedHayashikawa

Added fsm_quantity field at Sale Order Line Level on Field Service Order and added conditional coloring( red) on Sale Order Line to signify that there is a discrepancy between the Ordered QTY vs the fsm_quantity. 

ART-PH2-31-00-2102-001232 -Expose FSM_Quantity field on FSO
https://pm.opensourceintegrators.com/web#id=14819&model=project.task&view_type=form&menu_id=176

2021-02-15 17:16 UTC, smangukiya approved these changes

2021-02-15 17:23 UTC, smangukiya commented on fieldservice_mobile/views/fsm_order_view.xml
> +        <field name="inherit_id" ref="artisent.fsm_order_artisent_changes"/>
@ReedHayashikawa Remove the artisent module dependency here and get the latest 12.0 branch before pushing your latest code changes related to this ticket. Thanks

2021-02-15 17:23 UTC, smangukiya requested changes
@ReedHayashikawa : Please attend to the requested change. Thanks

2021-02-19 23:34 UTC, closed without merging

2021-02-19 23:35 UTC, ReedHayashikawa commented
Closed this PR because the page I am referencing is artisent specific.