[14.0][MIG]osi_analytic_segments_stock_scrap
ursais/osi-addons pull request #341
Opened 2021-06-17 10:03 UTC by hpatelserpentcs

Migrated the module osi_analytic_segments_stock_scrap in v14.

2021-06-17 16:24 UTC, patrickrwilson requested changes
OSI scrap reason code has moved to OCA, please update dependency.

2021-06-17 16:24 UTC, patrickrwilson commented on osi_analytic_segments_stock_scrap/__manifest__.py
> +        "osi_scrap_reason_code",
scrap reason code was moved to OCA which we should use. The module does work with using the OCA module instead so just changing this line is all that's needed.

2021-06-23 14:08 UTC, patrickrwilson approved these changes
Tested and LGTM

2021-06-23 21:25 UTC, smangukiya approved these changes
LGTM.

2021-07-01 17:43 UTC, merged