[14.0][Mig] osi_payment_method
ursais/osi-addons pull request #344
Opened 2021-06-21 12:28 UTC by Freni-OSI

2021-06-28 17:28 UTC, patrickrwilson requested changes
Tested and works, just need readme updated and copyright dates updated.

2021-06-28 17:28 UTC, patrickrwilson commented on osi_payment_method/__init__.py
> +# Copyright (C) 2019 Open Source Integrators
Update copyright date on all files it's referenced.

2021-06-28 17:28 UTC, patrickrwilson commented on osi_payment_method/README.rst
> +* Go to the "Sales & Purchase" tab
It looks like this field is now in the 'Accounting' tab so this should be updated.

2021-07-13 19:35 UTC, patrickrwilson approved these changes
Tested and works. LGTM

2021-07-21 20:23 UTC, osi-scampbell approved these changes

2021-07-21 21:47 UTC, merged