[14.0][MIG] helpdesk_ticket_parent
ursais/osi-addons pull request #354
Opened 2021-07-01 12:50 UTC by Freni-OSI

2021-07-12 15:52 UTC, patrickrwilson approved these changes
Tested and works. LGTM

2021-07-12 15:58 UTC, smangukiya requested changes
@Freni-OSI : Remove setup files other than helpdesk_ticket_parent module. (i.e. unwanted files are there from osi_analytic_segments_purchase, osi_analytic_segments_expense, etc modules). Rest is ok.

2021-07-12 16:26 UTC, osi-scampbell approved these changes

2021-07-13 10:17 UTC, Freni-OSI commented
> @Freni-OSI : Remove setup files other than helpdesk_ticket_parent module. (i.e. unwanted files are there from osi_analytic_segments_purchase, osi_analytic_segments_expense, etc modules). Rest is ok.

Done. Thanks

2021-07-16 18:35 UTC, merged