[14.0] [ADD] Added new module to print US check in MICR font. (Ticket #17462)
ursais/osi-addons pull request #436
Opened 2022-03-21 06:48 UTC by Chandresh-OSI

Ticket: https://pm.opensourceintegrators.com/web?debug=0#id=17462&action=324&model=helpdesk.ticket&view_type=form&menu_id=218

2022-03-21 20:02 UTC, patrickrwilson commented on l10n_us_check_printing_micr/report/print_check.xml
> +<?xml version="1.0" encoding="utf-8" ?>
pre-commit reformatting needed throughout entire module.

2022-03-21 20:02 UTC, patrickrwilson commented on l10n_us_check_printing_micr/report/print_check.xml
> +                        class="col-8 float-right"
I'm getting the following error related to the signature. I originally thought it was because I didn't upload the signature (which blank should be allowed) but the error showed even after adding a signature:
  File "c:\Odoo\Odoo14\server\odoo\addons\base\models\qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'bool' object has no attribute 'replace'
Traceback (most recent call last):
  File "c:\Odoo\Odoo14\server\odoo\addons\base\models\qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_us_check_printing_micr_ckus_check_micr_477
  File "c:\Odoo\Odoo14\server\odoo\addons\base\models\ir_qweb.py", line 380, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "c:\Odoo\Odoo14\server\odoo\addons\web\models\ir_qweb.py", line 73, in record_to_html
    src, src_zoom = self._get_src_urls(record, field_name, options)
  File "c:\Odoo\Odoo14\server\odoo\addons\web\models\ir_qweb.py", line 47, in _get_src_urls
    filename = filename.replace('/', '-').replace('\\', '-').replace('..', '--')
AttributeError: 'bool' object has no attribute 'replace'

Error to render compiling AST
AttributeError: 'bool' object has no attribute 'replace'
Template: l10n_us_check_printing_micr.ckus_check_micr
Path: /t/div/div[6]/div[2]
Node: <div class="col-8 float-right" t-field="o.partner_bank_id.signature_180" t-options="{&quot;widget&quot;: &quot;image&quot;, &quot;style&quot;:&quot;float: right;&quot;}"/>

2022-03-21 20:02 UTC, patrickrwilson commented on l10n_us_check_printing_micr/report/print_check.xml
> +            <span t-esc="o.partner_bank_id.bank_id.routing_number" />
I commented out the signature line so I can continue testing, however I get the following error when printing the check:

2022-03-21 20:09 UTC, patrickrwilson requested changes
@Freni-OSI here is my initial review. I couldn't get it to work to print a check so I've tried to add the errors I got in the review. Reach out to me if you need more info.

2022-03-21 20:09 UTC, patrickrwilson commented on l10n_us_check_printing_micr/models/res_partner_bank.py
> +    signature_180 = fields.Image(max_width=180, max_height=128, store=True)
Please add string="Signature"

2022-03-24 13:21 UTC, patrickrwilson commented
@Freni-OSI Seems we are getting closer but it's not working as expected. Please see the following points fix the issues described below:
CC: @Chandresh-OSI 

1. Update readme as it has some references to the scrap module. Also add configuration instructions for how to setup an account with routing number and signature.
2. When printing the check, we are missing items and formatting needs adjusting, see screenshots below...
3. Fix pre-commit

Here is the account number I setup that is on the bank journal: 
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/36892066/159923390-c4498bd1-35c6-48a3-b764-d554c8e8efb0.png">

And here is the check that printed, I've marked the issues with it:
![image](https://user-images.githubusercontent.com/36892066/159925082-601c22c0-dbf5-4866-81cd-df58d9eb26b2.png)

2022-03-29 07:54 UTC, dreispt commented
@Freni-OSI Anything blocking this form being worked on? Thanks

2022-03-31 10:05 UTC, Freni-OSI commented
> @Freni-OSI Seems we are getting closer but it's not working as expected. Please see the following points fix the issues described below: CC: @Chandresh-OSI
> 
> 1. Update readme as it has some references to the scrap module. Also add configuration instructions for how to setup an account with routing number and signature.
> 2. When printing the check, we are missing items and formatting needs adjusting, see screenshots below...
> 3. Fix pre-commit
> 4. The signature isn't showing on the report (and a line below the signature)
> 
> Here is the account number I setup that is on the bank journal: <img alt="image" width="1283" src="https://user-images.githubusercontent.com/36892066/159923390-c4498bd1-35c6-48a3-b764-d554c8e8efb0.png">
> 
> And here is the check that printed, I've marked the issues with it: ![image](https://user-images.githu
[Check Top .pdf](https://github.com/ursais/osi-addons/files/8388255/Check.Top.pdf)
busercontent.com/36892066/159925082-601c22c0-dbf5-4866-81cd-df58d9eb26b2.png)

@patrickrwilson Here's How it looks in my system. MICR is working perfectly. try installing from the font folder. PFA.
CC: @Chandresh-OSI

2022-04-07 11:00 UTC, dreispt commented
@Chandresh-OSI Is still still a WIP? The build is red.

2022-04-07 11:28 UTC, dreispt commented
@Chandresh-OSI can you update the configuration doc with an example of the steps needed to install the font, on a Linux/Debian system?

2022-04-08 10:01 UTC, dreispt commented
@Chandresh-OSI  @patrickrwilson I fixed the font installation, see the extra commit.

Result: 
![image](https://user-images.githubusercontent.com/1246629/162413722-54ecc261-eaf7-420b-a823-2fa4b4ff9563.png)

2022-10-21 20:31 UTC, closed without merging