[ADD] Fieldservice Agreement Helpdesk
ursais/osi-addons pull request #98
Opened 2019-05-28 17:30 UTC by osi-scampbell

This module links Field Service, Agreements, and Helpdesk together.

2019-05-28 18:48 UTC, max3903 approved these changes
LGTM

2019-05-28 18:49 UTC, max3903 commented on fieldservice_agreement_helpdesk/__manifest__.py
> +    "installable": True,
```suggestion
    "installable": True,
    "auto_install": True,
```

2019-05-28 18:53 UTC, max3903 commented on fieldservice_agreement_helpdesk/views/fsm_order.xml
> +                <attribute name="context">{'default_agreement_id': agreement_id}</attribute>
@osi-scampbell There is no agreement_id field on agreement. You probably want to set the customer field of the agreement:

```
<attribute name="context">{'default_partner_id': partner_id}</attribute>
```

2019-05-28 18:54 UTC, max3903 commented on fieldservice_agreement_helpdesk/views/fsm_order.xml
> +                <attribute name="context">{'default_serviceprofile_id': serviceprofile_id}</attribute>
```suggestion
                <attribute name="context">{'default_agreement_id': agreement_id}</attribute>
```

2019-05-28 18:55 UTC, max3903 requested changes
Minor changes.

2019-05-28 18:59 UTC, max3903 commented on fieldservice_agreement_helpdesk/README.rst
> +This module links Field Service, Agreements, and Helpdesk together.
```suggestion
This module links Field Service, Agreements and Help Desk together by:

* setting the agreement fields when creating Field Service orders from a ticket.
```

2019-05-29 17:05 UTC, max3903 commented on fieldservice_agreement_helpdesk/views/fsm_order.xml
> +                <attribute name="context">{'default_serviceprofile_id': serviceprofile_id}</attribute>
Ping @osi-scampbell

2019-05-29 20:23 UTC, osi-scampbell commented on fieldservice_agreement_helpdesk/views/fsm_order.xml
> +                <attribute name="context">{'default_serviceprofile_id': serviceprofile_id}</attribute>
Removed fsm_order.xml. Will make changes under fieldservice_agreement.

2019-05-30 03:33 UTC, max3903 approved these changes

2019-05-30 03:33 UTC, merged